# Generated by Django 4.2.30 on 2026-04-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='그룹키')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='코드값')),
                ('name', models.CharField(max_length=100, verbose_name='코드명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='core.codegroup', verbose_name='코드그룹')),
            ],
            options={
                'ordering': ['group__sort_order', 'group__key', 'sort_order', 'code'],
                'unique_together': {('group', 'code')},
            },
        ),
    ]
