# Generated by Django 4.2.30 on 2026-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=200, verbose_name='시스템명(참고)')),
                ('name', models.CharField(max_length=100, verbose_name='성명')),
                ('role', models.CharField(blank=True, choices=[('customer_it', '고객사 IT 담당'), ('sk_owner', 'Infa 담당자(SK)'), ('partner', '협력사 담당'), ('developer', '개발담당'), ('operator', '운영담당')], max_length=20, verbose_name='역할')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='업체명')),
                ('employee_no', models.CharField(blank=True, max_length=50, verbose_name='사번')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='메일주소')),
                ('ext_email', models.EmailField(blank=True, max_length=254, verbose_name='외부메일주소')),
                ('resident', models.BooleanField(default=False, verbose_name='상주여부')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='구분')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='시스템명')),
                ('system_type', models.CharField(blank=True, max_length=100, verbose_name='시스템 구분')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('operation_type', models.CharField(blank=True, max_length=50, verbose_name='운영구분')),
                ('service_grade', models.CharField(blank=True, max_length=50, verbose_name='서비스 등급')),
                ('service_level', models.CharField(blank=True, max_length=50, verbose_name='서비스 수준')),
                ('owner_company', models.CharField(blank=True, max_length=100, verbose_name='담당 회사')),
                ('owner_dept', models.CharField(blank=True, max_length=100, verbose_name='담당 부서')),
                ('owner_manager', models.CharField(blank=True, max_length=100, verbose_name='담당 팀장')),
                ('owner_person', models.CharField(blank=True, max_length=100, verbose_name='담당자')),
                ('opened_at', models.DateField(blank=True, null=True, verbose_name='서비스 오픈일')),
                ('frontend_stack', models.CharField(blank=True, max_length=200, verbose_name='Front-End')),
                ('backend_stack', models.CharField(blank=True, max_length=200, verbose_name='Back-End')),
                ('infra_env', models.CharField(blank=True, max_length=100, verbose_name='운영환경')),
                ('automation_tool', models.CharField(blank=True, max_length=100, verbose_name='자동화도구')),
                ('monitoring', models.CharField(blank=True, max_length=100, verbose_name='모니터링')),
                ('itgc', models.BooleanField(default=False, verbose_name='ITGC 여부')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=200, verbose_name='시스템명(참고)')),
                ('name', models.CharField(max_length=200, verbose_name='컴포넌트/컨트롤 명')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='버전')),
                ('released_year', models.IntegerField(blank=True, null=True, verbose_name='출시년도')),
                ('eos', models.BooleanField(default=False, verbose_name='EOS 여부')),
                ('update_support', models.BooleanField(default=True, verbose_name='업데이트 지원 여부')),
                ('comp_type', models.CharField(blank=True, max_length=100, verbose_name='컴포넌트 유형')),
                ('usage', models.CharField(blank=True, max_length=200, verbose_name='사용 용도')),
                ('license', models.CharField(blank=True, max_length=100, verbose_name='라이선스')),
                ('install_method', models.CharField(blank=True, max_length=100, verbose_name='설치방법')),
                ('renew_date', models.DateField(blank=True, null=True, verbose_name='(구독 시) 갱신일')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='운영자(작성자)')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
