# Generated by Django 4.2.30 on 2026-04-22 16:13

from django.db import migrations, models


def fill_management_numbers(apps, schema_editor):
    ServiceMaster = apps.get_model("masters", "ServiceMaster")
    PersonMaster = apps.get_model("masters", "PersonMaster")
    Component = apps.get_model("masters", "Component")

    for idx, row in enumerate(ServiceMaster.objects.order_by("pk"), start=1):
        row.service_mgmt_no = f"SVC{idx:04d}"
        row.save(update_fields=["service_mgmt_no"])

    for idx, row in enumerate(PersonMaster.objects.order_by("pk"), start=1):
        row.person_mgmt_no = f"PRS{idx:04d}"
        row.save(update_fields=["person_mgmt_no"])

    for idx, row in enumerate(Component.objects.order_by("pk"), start=1):
        row.asset_mgmt_no = f"AST{idx:04d}"
        row.save(update_fields=["asset_mgmt_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_personmaster_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='asset_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='자산관리번호'),
        ),
        migrations.AddField(
            model_name='personmaster',
            name='person_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='담당자관리번호'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='서비스관리번호'),
        ),
        migrations.RunPython(fill_management_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='component',
            name='asset_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='자산관리번호'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='person_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='담당자관리번호'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='서비스관리번호'),
        ),
    ]
