# Generated by Django 4.2.30 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_component_asset_mgmt_no_personmaster_person_mgmt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='appl_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Appl. 담당자'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='bs',
            field=models.BooleanField(default=False, verbose_name='BS'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='bs_share_note',
            field=models.TextField(blank=True, verbose_name='BS Share 비고'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='bs_share_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='BS Share 비율'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='build_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='구축 구분'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='cloud_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cloud 구분'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='customer_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='고객사 담당자'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='daejung',
            field=models.BooleanField(default=False, verbose_name='대정'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='db_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='DB 담당자'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='dbms',
            field=models.CharField(blank=True, max_length=100, verbose_name='DBMS'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='deploy_tool',
            field=models.CharField(blank=True, max_length=100, verbose_name='배포도구'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='dev_framework',
            field=models.CharField(blank=True, max_length=100, verbose_name='개발 F/W'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='dev_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='개발 언어'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='dy',
            field=models.BooleanField(default=False, verbose_name='DY'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='entis',
            field=models.BooleanField(default=False, verbose_name='엔티스'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='gc',
            field=models.BooleanField(default=False, verbose_name='GC'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='monitoring_tool',
            field=models.CharField(blank=True, max_length=100, verbose_name='모니터링도구'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='mu',
            field=models.BooleanField(default=False, verbose_name='MU'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='partner_operator',
            field=models.CharField(blank=True, max_length=100, verbose_name='협력사 운영자'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='pharma',
            field=models.BooleanField(default=False, verbose_name='파마'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='plasma',
            field=models.BooleanField(default=False, verbose_name='플라즈마'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='scm_tool',
            field=models.CharField(blank=True, max_length=100, verbose_name='형상관리'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='server_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='서버 담당자'),
        ),
    ]
