# Generated by Django 4.2.30 on 2026-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_servicemaster_appl_owner_servicemaster_bs_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('asset_mgmt_no', 'name'), name='uniq_component_mgmt_no_name'),
        ),
        migrations.AddConstraint(
            model_name='personmaster',
            constraint=models.UniqueConstraint(fields=('person_mgmt_no', 'name', 'system_name'), name='uniq_person_mgmt_no_name_system'),
        ),
        migrations.AddConstraint(
            model_name='servicemaster',
            constraint=models.UniqueConstraint(fields=('service_mgmt_no', 'name'), name='uniq_service_mgmt_no_name'),
        ),
    ]
