# Generated by Django 4.2.30 on 2026-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_component_uniq_component_mgmt_no_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='name',
            field=models.CharField(max_length=200, verbose_name='시스템명'),
        ),
    ]
