# Generated by Django 4.2.30 on 2026-04-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_servicemaster_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='component',
            name='uniq_component_mgmt_no_name',
        ),
        migrations.RemoveConstraint(
            model_name='personmaster',
            name='uniq_person_mgmt_no_name_system',
        ),
        migrations.RemoveConstraint(
            model_name='servicemaster',
            name='uniq_service_mgmt_no_name',
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set(),
        ),
    ]
