# Generated by Django 4.2.30 on 2026-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_remove_component_uniq_component_mgmt_no_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmaster',
            name='deployed_at',
            field=models.DateField(blank=True, null=True, verbose_name='투입 일자'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='소속 조직'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='내부 메일'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='ext_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='외부 메일'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='resident',
            field=models.BooleanField(default=False, verbose_name='상주 여부'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='system_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='담당 시스템'),
        ),
    ]
