# Generated by Django 4.2.30 on 2026-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_personmaster_deployed_at_alter_personmaster_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='eos',
        ),
        migrations.RemoveField(
            model_name='component',
            name='install_method',
        ),
        migrations.RemoveField(
            model_name='component',
            name='license',
        ),
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
        migrations.RemoveField(
            model_name='component',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='component',
            name='released_year',
        ),
        migrations.RemoveField(
            model_name='component',
            name='renew_date',
        ),
        migrations.RemoveField(
            model_name='component',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='component',
            name='update_support',
        ),
        migrations.RemoveField(
            model_name='component',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='component',
            name='version',
        ),
        migrations.AddField(
            model_name='component',
            name='cert_format',
            field=models.CharField(blank=True, max_length=100, verbose_name='인증서 포맷'),
        ),
        migrations.AddField(
            model_name='component',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='component',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='component',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='위치'),
        ),
        migrations.AddField(
            model_name='component',
            name='mw',
            field=models.CharField(blank=True, max_length=100, verbose_name='MW'),
        ),
        migrations.AddField(
            model_name='component',
            name='network_zone',
            field=models.CharField(blank=True, max_length=100, verbose_name='네트웍 구분'),
        ),
        migrations.AddField(
            model_name='component',
            name='operation_dev',
            field=models.CharField(blank=True, max_length=50, verbose_name='운영/개발'),
        ),
        migrations.AddField(
            model_name='component',
            name='os_dbms',
            field=models.CharField(blank=True, max_length=200, verbose_name='OS/DBMS'),
        ),
        migrations.AddField(
            model_name='component',
            name='platform_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='플랫폼 구분'),
        ),
        migrations.AddField(
            model_name='component',
            name='port',
            field=models.CharField(blank=True, max_length=20, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='component',
            name='remark1',
            field=models.TextField(blank=True, verbose_name='비고1'),
        ),
        migrations.AddField(
            model_name='component',
            name='remark2',
            field=models.TextField(blank=True, verbose_name='비고2'),
        ),
        migrations.AddField(
            model_name='component',
            name='server_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='서버 구분'),
        ),
        migrations.AddField(
            model_name='component',
            name='ssl_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='SSL 도메인'),
        ),
        migrations.AddField(
            model_name='component',
            name='url_or_db_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL/DB명'),
        ),
    ]
