# Generated by Django 4.2.30 on 2026-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_remove_component_comp_type_remove_component_eos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='system_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='시스템명'),
        ),
    ]
