# Generated by Django 4.2.30 on 2026-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_component_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='name',
            field=models.CharField(max_length=200, verbose_name='서비스명'),
        ),
    ]
