# Generated by Django 4.2.30 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0011_alter_servicemaster_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemaster",
            name="partner_operator",
            field=models.CharField(blank=True, max_length=100, verbose_name="Appl. 운영자"),
        ),
    ]
