# Generated by Django 4.2.30 on 2026-04-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_servicemaster_partner_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemaster',
            name='cloud_type',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='dbms',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='dev_framework',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='dev_language',
        ),
    ]
