# Generated by Django 4.2.30 on 2026-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_remove_servicemaster_cloud_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_mgmt_no', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='컴포넌트관리번호')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='Hostname')),
                ('system_name', models.CharField(blank=True, max_length=200, verbose_name='시스템명')),
                ('server_type', models.CharField(blank=True, max_length=100, verbose_name='서버 구분')),
                ('operation_dev', models.CharField(blank=True, max_length=50, verbose_name='운영/개발')),
                ('platform_type', models.CharField(blank=True, max_length=100, verbose_name='플랫폼 구분')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('network_zone', models.CharField(blank=True, max_length=100, verbose_name='네트웍 구분')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('port', models.CharField(blank=True, max_length=20, verbose_name='Port')),
                ('mw', models.CharField(blank=True, max_length=100, verbose_name='MW')),
                ('os_dbms', models.CharField(blank=True, max_length=200, verbose_name='OS/DBMS')),
                ('url_or_db_name', models.CharField(blank=True, max_length=300, verbose_name='URL/DB명')),
                ('ssl_domain', models.CharField(blank=True, max_length=200, verbose_name='SSL 도메인')),
                ('cert_format', models.CharField(blank=True, max_length=100, verbose_name='인증서 포맷')),
                ('remark1', models.TextField(blank=True, verbose_name='비고1')),
                ('remark2', models.TextField(blank=True, verbose_name='비고2')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
            ],
        ),
    ]
