# Generated by Django 4.2.30 on 2026-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_componentmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmaster',
            name='component_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='컴포넌트번호'),
        ),
    ]
