# Generated by Django 4.2.30 on 2026-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_alter_componentmaster_component_mgmt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='db',
            field=models.CharField(blank=True, max_length=100, verbose_name='DB'),
        ),
        migrations.AddField(
            model_name='component',
            name='middleware',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middleware'),
        ),
        migrations.AddField(
            model_name='component',
            name='os',
            field=models.CharField(blank=True, max_length=100, verbose_name='OS'),
        ),
    ]
