# Generated by Django 4.2.30 on 2026-05-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_code_related_code'),
        ('masters', '0019_component_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCode',
            fields=[
                ('attribute_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='속성 코드')),
                ('name', models.CharField(max_length=200, verbose_name='속성명')),
                ('code_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_codes', to='core.codegroup', verbose_name='코드 그룹')),
                ('data_type_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_data_type_codes', to='core.code', verbose_name='데이터 타입')),
                ('required_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_required_codes', to='core.code', verbose_name='필수 여부')),
                ('searchable_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_searchable_codes', to='core.code', verbose_name='검색 가능 여부')),
                ('target_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_target_codes', to='core.code', verbose_name='적용 대상')),
            ],
            options={
                'ordering': ['attribute_code'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이력 ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='테이블 명')),
                ('pk_value', models.CharField(max_length=100, verbose_name='PK 값')),
                ('field_name', models.CharField(max_length=100, verbose_name='변경 필드')),
                ('before_value', models.TextField(blank=True, verbose_name='변경 전 값')),
                ('after_value', models.TextField(blank=True, verbose_name='변경 후 값')),
                ('changed_by', models.CharField(blank=True, max_length=100, verbose_name='변경자')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일')),
            ],
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['asset_mgmt_no', 'hostname']},
        ),
        migrations.AlterModelOptions(
            name='componentmaster',
            options={'ordering': ['component_mgmt_no', 'product_name']},
        ),
        migrations.AlterModelOptions(
            name='personmaster',
            options={'ordering': ['person_mgmt_no', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicemaster',
            options={'ordering': ['service_mgmt_no', 'name']},
        ),
        migrations.RemoveField(
            model_name='component',
            name='cert_format',
        ),
        migrations.RemoveField(
            model_name='component',
            name='db',
        ),
        migrations.RemoveField(
            model_name='component',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='component',
            name='location',
        ),
        migrations.RemoveField(
            model_name='component',
            name='middleware',
        ),
        migrations.RemoveField(
            model_name='component',
            name='mw',
        ),
        migrations.RemoveField(
            model_name='component',
            name='network_zone',
        ),
        migrations.RemoveField(
            model_name='component',
            name='operation_dev',
        ),
        migrations.RemoveField(
            model_name='component',
            name='os',
        ),
        migrations.RemoveField(
            model_name='component',
            name='os_dbms',
        ),
        migrations.RemoveField(
            model_name='component',
            name='platform_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='remark1',
        ),
        migrations.RemoveField(
            model_name='component',
            name='remark2',
        ),
        migrations.RemoveField(
            model_name='component',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='component',
            name='server_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='ssl_domain',
        ),
        migrations.RemoveField(
            model_name='component',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='component',
            name='url_or_db_name',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='remark1',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='remark2',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='server_type',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='componentmaster',
            name='url_or_db_name',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='ext_email',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personmaster',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='appl_owner',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='automation_tool',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='backend_stack',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='bs_share_note',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='bs_share_ratio',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='build_type',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='customer_owner',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='daejung',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='db_owner',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='deploy_tool',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='dy',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='entis',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='frontend_stack',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='gc',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='infra_env',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='itgc',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='monitoring_tool',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='mu',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='owner_company',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='owner_dept',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='owner_manager',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='owner_person',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='partner_operator',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='pharma',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='plasma',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='scm_tool',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='server_owner',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='service_grade',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='service_level',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='system_type',
        ),
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='component',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='component',
            name='infra_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_infra_types', to='core.code', verbose_name='인프라 구분'),
        ),
        migrations.AddField(
            model_name='component',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_locations', to='core.code', verbose_name='인프라 위치'),
        ),
        migrations.AddField(
            model_name='component',
            name='network_zone_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_network_zones', to='core.code', verbose_name='네트웍 구분'),
        ),
        migrations.AddField(
            model_name='component',
            name='operation_dev_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_operation_types', to='core.code', verbose_name='운영/개발'),
        ),
        migrations.AddField(
            model_name='component',
            name='server_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_types', to='core.code', verbose_name='구성 유형'),
        ),
        migrations.AddField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='component',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='component',
            name='url',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='component_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_types', to='core.code', verbose_name='컴포넌트 유형'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='cpe_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='CPE 이름'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='eol_date',
            field=models.DateField(blank=True, null=True, verbose_name='EOL 날짜'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='eos_date',
            field=models.DateField(blank=True, null=True, verbose_name='EOS 날짜'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='제품명'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='support_status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_support_statuses', to='core.code', verbose_name='지원 여부'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='벤더명'),
        ),
        migrations.AddField(
            model_name='componentmaster',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='버전'),
        ),
        migrations.AddField(
            model_name='personmaster',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='종료 일자'),
        ),
        migrations.AddField(
            model_name='personmaster',
            name='external_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='외부 이메일'),
        ),
        migrations.AddField(
            model_name='personmaster',
            name='role_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_roles', to='core.code', verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='personmaster',
            name='status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_statuses', to='core.code', verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='build_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_build_type_items', to='core.code', verbose_name='구축 구분'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='category_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_category_items', to='core.code', verbose_name='서비스 분류'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='서비스 종료일'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='itgc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_itgc_items', to='core.code', verbose_name='ITGC 여부'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_grade_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_grade_items', to='core.code', verbose_name='서비스 등급'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_status_items', to='core.code', verbose_name='서비스 상태'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='component',
            name='asset_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='구성 ID'),
        ),
        migrations.AlterField(
            model_name='component',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='서버 명'),
        ),
        migrations.AlterField(
            model_name='componentmaster',
            name='component_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='컴포넌트 ID'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='내부 이메일'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='employee_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='사번'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='person_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='담당자 ID'),
        ),
        migrations.AlterField(
            model_name='personmaster',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='name',
            field=models.CharField(max_length=200, verbose_name='서비스 명'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_mgmt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='서비스 ID'),
        ),
        migrations.CreateModel(
            name='ServicePersonMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='서비스 담당자 매핑 ID')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_person_mappings', to='masters.personmaster', verbose_name='담당자 ID')),
                ('role_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_person_mapping_roles', to='core.code', verbose_name='역할')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_person_mappings', to='masters.servicemaster', verbose_name='서비스 ID')),
                ('status_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_person_mapping_statuses', to='core.code', verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfigurationMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='서비스 구성 매핑 ID')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_configuration_mappings', to='masters.component', verbose_name='구성 ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_configuration_mappings', to='masters.servicemaster', verbose_name='서비스 ID')),
                ('status_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_configuration_mapping_statuses', to='core.code', verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationComponentMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='구성 컴포넌트 ID')),
                ('install_path', models.CharField(blank=True, max_length=300, verbose_name='설치 경로')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_component_mappings', to='masters.componentmaster', verbose_name='컴포넌트 ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_component_mappings', to='masters.component', verbose_name='구성 ID')),
                ('use_yn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_component_use_flags', to='core.code', verbose_name='사용 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='인증서 ID')),
                ('domain', models.CharField(max_length=200, verbose_name='도메인')),
                ('cert_format', models.CharField(blank=True, max_length=100, verbose_name='인증서 포맷')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='발급기관')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='masters.component', verbose_name='구성 ID')),
                ('use_yn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_use_flags', to='core.code', verbose_name='사용 여부')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='서비스 속성 ID')),
                ('value', models.TextField(blank=True, verbose_name='속성 값')),
                ('attribute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attributes', to='masters.attributecode', verbose_name='속성 코드')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attributes', to='masters.servicemaster', verbose_name='서비스 ID')),
            ],
            options={
                'unique_together': {('service', 'attribute_code')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='구성정보 속성 ID')),
                ('value', models.TextField(blank=True, verbose_name='속성 값')),
                ('attribute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_attributes', to='masters.attributecode', verbose_name='속성 코드')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_attributes', to='masters.component', verbose_name='구성 ID')),
            ],
            options={
                'unique_together': {('configuration', 'attribute_code')},
            },
        ),
    ]
