# Generated by Django 4.2.30 on 2026-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_code_related_code'),
        ('masters', '0020_attributecode_changehistory_alter_component_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='ConfigurationMaster',
        ),
        migrations.RenameModel(
            old_name='ComponentMaster',
            new_name='Component',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['component_mgmt_no', 'product_name']},
        ),
        migrations.AlterModelOptions(
            name='configurationmaster',
            options={'ordering': ['asset_mgmt_no', 'hostname']},
        ),
    ]
