# Generated by Django 4.2.30 on 2026-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_configurationmaster_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='컴포넌트명'),
        ),
        migrations.AlterField(
            model_name='configurationmaster',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='구성명'),
        ),
    ]
