# Generated by Django 4.2.30 on 2026-05-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_personmaster_employee_no_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAlias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='컴포넌트 alias ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='제품명')),
                ('alias', models.CharField(max_length=200, verbose_name='Alias')),
            ],
            options={
                'verbose_name': '컴포넌트 alias',
                'verbose_name_plural': '컴포넌트 alias',
                'ordering': ['product_name', 'alias'],
                'indexes': [models.Index(fields=['alias'], name='masters_com_alias_6edecf_idx'), models.Index(fields=['product_name'], name='masters_com_product_1fd27d_idx')],
                'unique_together': {('product_name', 'alias')},
            },
        ),
    ]
