# Generated by Django 4.2.30 on 2026-05-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_code_related_code'),
        ('masters', '0027_componentalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='ito_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ito_items', to='core.code', verbose_name='ITO'),
        ),
    ]
