# Generated by Django 4.2.30 on 2026-04-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraAsset',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=200, verbose_name='시스템명')),
                ('use_flag', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('devops_type', models.CharField(blank=True, choices=[('DEV', '개발'), ('OPS', '운영'), ('BOTH', '개발/운영')], max_length=5, verbose_name='개발/운영')),
                ('infra_type', models.CharField(blank=True, choices=[('ONPREM', 'On-Premise'), ('AWS', 'AWS'), ('OTHER', '기타')], max_length=10, verbose_name='인프라 구분')),
                ('network_zone', models.CharField(blank=True, choices=[('DMZ', 'DMZ'), ('SF', 'Server Farm'), ('ETC', '기타')], max_length=5, verbose_name='네트웍 구분')),
                ('platform_type', models.CharField(blank=True, choices=[('WEB', 'WEB'), ('CS', 'CS'), ('MOBILE', 'Mobile'), ('ETC', '기타')], max_length=10, verbose_name='플랫폼 구분')),
                ('web', models.CharField(blank=True, max_length=100, verbose_name='WEB')),
                ('was', models.CharField(blank=True, max_length=100, verbose_name='WAS')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='Hostname')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('port', models.CharField(blank=True, max_length=20, verbose_name='Port')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='OS')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('ssl_domain', models.CharField(blank=True, max_length=200, verbose_name='SSL 도메인')),
                ('cert_format', models.CharField(blank=True, max_length=50, verbose_name='인증서 포맷')),
                ('db_hostname', models.CharField(blank=True, max_length=200, verbose_name='DB Hostname')),
                ('db_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='DB IP')),
                ('db_port', models.CharField(blank=True, max_length=20, verbose_name='DB Port')),
                ('db_name', models.CharField(blank=True, max_length=100, verbose_name='DB명')),
                ('dbms', models.CharField(blank=True, max_length=100, verbose_name='DBMS')),
                ('db_size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='DB Size(GB)')),
                ('db_encrypted', models.BooleanField(default=False, verbose_name='DB암호화')),
                ('remark1', models.TextField(blank=True, verbose_name='비고1')),
                ('remark2', models.TextField(blank=True, verbose_name='비고2')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='추가필드')),
                ('components', models.ManyToManyField(blank=True, to='masters.component', verbose_name='컴포넌트')),
                ('dt_team_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_dt', to='masters.personmaster', verbose_name='DT팀 담당')),
                ('extra_persons', models.ManyToManyField(blank=True, related_name='assets_extra', to='masters.personmaster', verbose_name='추가 담당자')),
                ('ito_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_ito', to='masters.personmaster', verbose_name='통합ITO 담당')),
                ('partner_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_partner', to='masters.personmaster', verbose_name='협력 담당')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.servicemaster', verbose_name='서비스')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
