# Generated by Django 4.2.30 on 2026-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraasset',
            name='devops_type',
            field=models.CharField(blank=True, max_length=5, verbose_name='개발/운영'),
        ),
        migrations.AlterField(
            model_name='infraasset',
            name='infra_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='인프라 구분'),
        ),
        migrations.AlterField(
            model_name='infraasset',
            name='network_zone',
            field=models.CharField(blank=True, max_length=5, verbose_name='네트웍 구분'),
        ),
        migrations.AlterField(
            model_name='infraasset',
            name='platform_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='플랫폼 구분'),
        ),
        migrations.AlterField(
            model_name='infraasset',
            name='use_flag',
            field=models.CharField(default='Y', max_length=1, verbose_name='사용여부'),
        ),
    ]
