# Generated by Django 4.2.30 on 2026-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_infraasset_devops_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraasset',
            name='asset_key',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='자산KEY'),
        ),
    ]
