# Generated by Django 4.2.30 on 2026-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_infraasset_asset_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='infraasset',
            constraint=models.UniqueConstraint(fields=('asset_key', 'system_name'), name='uniq_asset_key_system_name'),
        ),
    ]
