# Generated by Django 4.2.30 on 2026-04-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_infraasset_uniq_asset_key_system_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='infraasset',
            name='uniq_asset_key_system_name',
        ),
    ]
