# Generated by Django 4.2.30 on 2026-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_infraasset_uniq_asset_key_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraasset',
            name='customer_owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='고객사 담당자'),
        ),
    ]
