# Generated by Django 4.2.30 on 2026-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_infraasset_customer_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraasset',
            name='appl_owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Appl. 담당자'),
        ),
        migrations.AddField(
            model_name='infraasset',
            name='partner_operator_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='협력사 운영자'),
        ),
    ]
