# Generated by Django 4.2.30 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_infraasset_appl_owner_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infraasset",
            name="partner_operator_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Appl. 운영자"),
        ),
    ]
