# Generated by Django 4.2.30 on 2026-05-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_configurationmaster_alter_component_options_and_more'),
        ('assets', '0011_infraasset_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraasset',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infra_assets', to='masters.configurationmaster', verbose_name='구성정보 마스터'),
        ),
    ]
