# Generated by Django 4.2.30 on 2026-05-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_integrated_view_preset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integratedviewpreset',
            new_name='web_integra_user_id_5f715b_idx',
            old_name='web_integra_user_id_8c3a6d_idx',
        ),
    ]
